### PR TITLE
Added command "addmoney"

### PR DESCRIPTION
**Pull request by Parsiuk**
I added command "addmoney". It's getting playerID by name, getting current amount of money, and then adds money to player account. I tried to follow original style. "Reason" or "detail" in setPlayerMoney has to be unique otherwise server will not accept transaction. I have that tested on my server.
## 

Regards,
Maciek

### CODE REVIEW

**Comment by bdew** [comment]
Any reason for not using addMoneyToBank?

Those separate getMoney/setMoney calls just scream potential race condition at me :P

**Comment by bdew** [comment]
I've experimented for a bit and it seems that addMoneyToBank does pretty much the same thing just without the potential race condition. The only minor difference is that it doesn't notify the player with a message in event window and it doesn't require the transaction detail to be unique.

Unless there's a good reason that i'm missing i'll change it to use that call.

**Comment by Parsiuk** [comment]
You're right, for some reason I thought "addMoneyToBank" adds money to kingdom bank. I didn't look what it's actually doing. Thnx for pointing it out.

**Comment by bdew** [comment]
Ok i've changed it to use that addMoneyToBank call, also made the detail string optional and made it output the response from the server.

**Comment by Parsiuk** [comment]
Great! Thank you for all your work. :)

**Pull request merged**
